//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NlnrPriceDyn.Logic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NlnrPriceDyn.Logic.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://catalog.api.onliner.by/search/products?query=.
        /// </summary>
        internal static string ApiCatalogueUrl {
            get {
                return ResourceManager.GetString("ApiCatalogueUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to catalog.onliner.by.
        /// </summary>
        internal static string CatalogueHost {
            get {
                return ResourceManager.GetString("CatalogueHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account/confirm-email?id={0}&amp;code={1}.
        /// </summary>
        internal static string EmailConfirmCallbackUrl {
            get {
                return ResourceManager.GetString("EmailConfirmCallbackUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, подтвердите свой адрес электронной почты пройдя по &lt;a href =&quot;{0}&quot;&gt;ссылке&lt;/a&gt;.
        /// </summary>
        internal static string EmailConfirmMsgBody {
            get {
                return ResourceManager.GetString("EmailConfirmMsgBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите свой адрес электронной почты.
        /// </summary>
        internal static string EmailConfirmMsgSubject {
            get {
                return ResourceManager.GetString("EmailConfirmMsgSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальная цена в каталоге на товар &quot;{0}&quot; из вашего списка составляет {1} руб..
        /// </summary>
        internal static string EmailProductLowPriceNotificationBody {
            get {
                return ResourceManager.GetString("EmailProductLowPriceNotificationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оповещение о снижении цены.
        /// </summary>
        internal static string EmailProductLowPriceNotificationSubject {
            get {
                return ResourceManager.GetString("EmailProductLowPriceNotificationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный URL продукта..
        /// </summary>
        internal static string ErrorIncorrectProductUrl {
            get {
                return ResourceManager.GetString("ErrorIncorrectProductUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный Id..
        /// </summary>
        internal static string ErrorIncorrectUserProductId {
            get {
                return ResourceManager.GetString("ErrorIncorrectUserProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Товар снят с производства..
        /// </summary>
        internal static string ErrorProductDiscontinued {
            get {
                return ResourceManager.GetString("ErrorProductDiscontinued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка сервера..
        /// </summary>
        internal static string ErrorServerError {
            get {
                return ResourceManager.GetString("ErrorServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrMaxUsersCountReached..
        /// </summary>
        internal static string MaxUsersErrCode {
            get {
                return ResourceManager.GetString("MaxUsersErrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрировано максимальное число пользователей..
        /// </summary>
        internal static string MaxUsersErrMsg {
            get {
                return ResourceManager.GetString("MaxUsersErrMsg", resourceCulture);
            }
        }
    }
}
