//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NlnrPriceDyn.Logic.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NlnrPriceDyn.Logic.Common.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный адрес электронной почты..
        /// </summary>
        internal static string ErrorIncorrectEmail {
            get {
                return ResourceManager.GetString("ErrorIncorrectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется численное значение..
        /// </summary>
        internal static string ErrorIncorrectNumericValue {
            get {
                return ResourceManager.GetString("ErrorIncorrectNumericValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароли не совпадают..
        /// </summary>
        internal static string ErrorPasswordsDontMatch {
            get {
                return ResourceManager.GetString("ErrorPasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина пароля должна быть не менее 6 символов..
        /// </summary>
        internal static string ErrorPasswordTooShort {
            get {
                return ResourceManager.GetString("ErrorPasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание продукта не должно быть пустым..
        /// </summary>
        internal static string ErrorProductTitleBlank {
            get {
                return ResourceManager.GetString("ErrorProductTitleBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный URL продукта..
        /// </summary>
        internal static string ErrorProductUrlBlank {
            get {
                return ResourceManager.GetString("ErrorProductUrlBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный Id пользователя..
        /// </summary>
        internal static string ErrorUserIdBlank {
            get {
                return ResourceManager.GetString("ErrorUserIdBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя не должно быть пустым..
        /// </summary>
        internal static string ErrorUserNameBlank {
            get {
                return ResourceManager.GetString("ErrorUserNameBlank", resourceCulture);
            }
        }
    }
}
